# Generated by Django 5.1.5 on 2025-03-19 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='remark_text',
            new_name='remark',
        ),
        migrations.AddField(
            model_name='deadline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deadline',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.task'),
        ),
        migrations.RemoveField(
            model_name='remark',
            name='students',
        ),
        migrations.AlterField(
            model_name='remark',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='faculty',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remark',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
