# Generated by Django 5.1.5 on 2025-03-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_rename_remark_text_remark_remark_deadline_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='students',
        ),
        migrations.AddField(
            model_name='remark',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_remarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
