# Generated by Django 5.1.5 on 2025-02-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_approvalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('syllabus_file', models.FileField(upload_to='syllabus/')),
            ],
        ),
    ]
