# Generated by Django 5.1.5 on 2025-03-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='delay_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='progress_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
