# Generated by Django 5.1.5 on 2025-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprogress_delay_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
